#!/usr/bin/env bash
# performing a 301 move permanent redirection

sudo apt-get -y update 
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/mail.yahoo.com permanent;"

sudo sed -i "s|servername_;|$string_for_replacement|" /etc/nginx/sites-enabled/default

sudo service nginx restart

