#!/usr/bin/env bash
# performing a 301 move permanent redirection

sudo apt-get -y update 
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="listen 80 default_server;\n\trewrite ^\/redirect_me https:\/\/youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart

