#!/usr/bin/env bash
#sets up custom header
sudo apt-get -y
sudo apt-get -y install nginx

#creadting an index page
sudo bash -c echo "Hello World!" | sudo tee /var/www/html/index.html

#performing a redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-enabled/default

#create a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

#Add a custom HTTP response header
sudo sed -i '/server_name _;/a\    add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default

#Test Configuration
sudo nginx -t
#Restart nginx services
sudo service nginx restart

