#!/bin/bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOL | sudo tee -a /etc/haproxy/haproxy.cfg
frontend haproxynode
	bind *:80
	mode http
	default_backend servers

backend servers
	mode http
	balance roundrobin
	option forwardfor
	http-request set-header X-Forwarded-Port %[dst_port]
	server 79001-web-01 54.87.181.20:80 check
	server 79001-web-02 18.234.129.115:80 check
EOL

# Restart HAProxy service
sudo systemctl restart haproxy.service

# Enable HAProxy service to start at boot time
sudo systemctl enable haproxy.service

