#!/usr/bin/env bash
#sets up load balancers

# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

file=/etc/haproxy/haproxy.cfg

# Configure HAProxy
sudo echo -e "frontend haproxynode
	\tbind *:80
	\tmode http
	\tdefault_backend servers" | sudo tee -a $file

sudo echo -e "backend servers
	\tmode http
	\tbalance roundrobin
	\toption forwardfor
	\thttp-request set-header X-Forwarded-Port %[dst_port]
	\tserver 79001-web-01 54.87.181.20:80 check
	\tserver 79001-web-02 18.234.129.115:80 check" | sudo tee -a $file

# Restart HAProxy service
sudo service haproxy restart
#sudo systemctl restart haproxy.service

# Enable HAProxy service to start at boot time
#sudo systemctl enable haproxy.service
