#!/bin/bash

# Install HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 79001-web-01 54.87.181.20:80 check
    server 79001-web-02 18.234.129.115:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy.service

# Enable HAProxy service to start at boot time
sudo systemctl enable haproxy.service

