#!/usr/bin/env bash
#Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Backup the default Nginx configuration
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak

# Modify the Nginx configuration to listen on port 80
sed -i 's/8080 default/80 default/g' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
