#!/usr/bin/env bash
# This script is displaying the time for 12 hours 59 mins using while loop

hours=0
minutes=1
count=1

while [ $count -le 70 ]
do
    printf "%02d:%02d\n" $hours $minutes

    minutes=$((minutes+1))
    if [ $minutes -eq 60 ]; then
        minutes=0
        hours=$((hours+1))
        if [ $hours -eq 13 ]; then
            hours=0
        fi
    fi

    count=$((count+1))
done | head -n 70
