#!/usr/bin/env bash
# This script is displaying the content of the current directory using for loop

for file in *
do
    # Check if file is not hidden
    if [[ ! "$file" =~ ^\..* ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
