#!/usr/bin/env bash
# return a page containing Hello Holberton when querying the root of it.

# Restart Container
docker restart 47ca3994a491 

#Check Docker Container Status:
docker ps

# Access the container and ensure it is running
docker exec -it 47ca3994a491 /bin/bash

# Test Environment
echo "I am in $(hostname) Docker container"

# create an index.html file in the appropriate directory to serve the "Hello Holberton" content.
echo "Hello Holberton" > /usr/local/apache2/htdocs/index.html

# Start Apache
sudo service apache2 start

# Test with localhost
curl localhost:8080
