#!/usr/bin/env bash
#prevent an attacker from logging in as root
pkill apache
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-enabled/default
chmod -R 777 /etc/nginx/
sudo -u nginx service nginx start

